[package]
name = "gpt4ocr"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenvy = "0.15.7"
image = "0.25.2"
kalosm = { git = "https://github.com/floneum/floneum", version = "0.2.2", features = ["vision", "cuda"] }
openai-api-rs = "5.0.4"
pdf2image = "0.1.2"
